import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="h-screen flex flex-col">
        <Header />
        <main class="flex-1 overflow-auto p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
